"use strict";
const DW_TAG_array_type = 0x01,
    DW_TAG_structure_type = 0x13,
    DW_TAG_union_type = 0x17,
    DW_TAG_enumeration_type = 0x04,
    DW_TAG_pointer_type = 0x0f,
    DW_TAG_typedef = 0x16,
    DW_TAG_base_type = 0x24,
    DW_TAG_const_type = 0x26,
    DW_TAG_volatile_type = 0x35,
    DW_TAG_restrict_type = 0x37,
    DW_TAG_variable = 0x34,
    DW_TAG_member = 0x0d,
    DW_TAG_subrange_type = 0x21;
const DW_AT_name = 0x03,
    DW_AT_byte_size = 0x0b,
    DW_AT_abstract_origin = 0x31,
    DW_AT_encoding = 0x3e,
    DW_AT_specification = 0x47,
    DW_AT_type = 0x49,
    DW_AT_location = 0x02,
    DW_AT_declaration = 0x3c,
    DW_AT_str_offsets_base = 0x72,
    DW_AT_data_member_location = 0x38,
    DW_AT_bit_size = 0x0d,
    DW_AT_bit_offset = 0x0c,
    DW_AT_data_bit_offset = 0x6b,
    DW_AT_count = 0x37,
    DW_AT_upper_bound = 0x2f;
const DW_ATE_boolean = 0x02,
    DW_ATE_float = 0x04,
    DW_ATE_signed = 0x05,
    DW_ATE_signed_char = 0x06,
    DW_ATE_unsigned = 0x07,
    DW_ATE_unsigned_char = 0x08;
module.exports = {
    DW_TAG_array_type,
    DW_TAG_structure_type,
    DW_TAG_union_type,
    DW_TAG_enumeration_type,
    DW_TAG_pointer_type,
    DW_TAG_typedef,
    DW_TAG_base_type,
    DW_TAG_const_type,
    DW_TAG_volatile_type,
    DW_TAG_restrict_type,
    DW_TAG_variable,
    DW_TAG_member,
    DW_TAG_subrange_type,
    DW_AT_name,
    DW_AT_byte_size,
    DW_AT_abstract_origin,
    DW_AT_encoding,
    DW_AT_specification,
    DW_AT_type,
    DW_AT_location,
    DW_AT_declaration,
    DW_AT_str_offsets_base,
    DW_AT_data_member_location,
    DW_AT_bit_size,
    DW_AT_bit_offset,
    DW_AT_data_bit_offset,
    DW_AT_count,
    DW_AT_upper_bound,
    DW_ATE_boolean,
    DW_ATE_float,
    DW_ATE_signed,
    DW_ATE_signed_char,
    DW_ATE_unsigned,
    DW_ATE_unsigned_char
};
