"use strict";
const { STRINGS, t, normalizeLang, jsonForScript } = require("./i18n");
const { loadWebviewAsset } = require("./webviewTemplate");
const sidebarCss = loadWebviewAsset("sidebar", "app.css");
const sidebarRenderer = loadWebviewAsset("sidebar", "renderer.js");
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function shiftSliderBounds(min,max,current,next){const lo=Number(min),hi=Number(max),from=Number(current),to=Number(next);if(![lo,hi,from,to].every(Number.isFinite)||hi<=lo||to>=lo&&to<=hi)return{min:lo,max:hi};const span=hi-lo,anchor=Math.min(hi,Math.max(lo,from)),offset=anchor-lo,newMin=to-offset;return{min:newMin,max:newMin+span}}
const icon={svd:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M8 7h8M8 12h8M8 17h8"/>',cube:'<path d="m12 2 9 5v10l-9 5-9-5V7zM3 7l9 5 9-5M12 12v10"/>',ioc:'<path d="M4 6h16M4 12h16M4 18h16"/><circle cx="8" cy="6" r="2"/><circle cx="16" cy="12" r="2"/><circle cx="10" cy="18" r="2"/>',scan:'<path d="M4 8V4h4m8 0h4v4m0 8v4h-4M8 20H4v-4M8 12h8m-4-4v8"/>',file:'<path d="M6 2h8l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/>',probe:'<rect x="5" y="7" width="14" height="10" rx="1"/><path d="M9 3v4m6-4v4M9 17v4m6-4v4M2 10h3m14 0h3M2 14h3m14 0h3"/>',chip:'<rect x="7" y="7" width="10" height="10" rx="1"/><path d="M9 2v3m6-3v3M9 19v3m6-3v3M2 9h3m-3 6h3m14-6h3m-3 6h3"/>',flash:'<path d="M13 2 5 14h7l-1 8 8-12h-7z"/>'};
function svg(name){return `<svg viewBox="0 0 24 24" aria-hidden="true">${icon[name]}</svg>`;}
function getModernWebviewContent(v,lang){
const L=normalizeLang(lang),tr=(k,p)=>t(L,k,p),notSel=tr('common.notSelected'),i18nJson=jsonForScript(STRINGS);
function rowVal(titleKey,value,cmd,name,optional='',extraClass=''){const val=value?('<small title="'+esc(value)+'">'+esc(value)+'</small>'):('<small data-i18n="common.notSelected">'+notSel+'</small>');return `<button class="tree-row ${extraClass}" data-command="${cmd}">${svg(name)}<span class="row-copy"><span data-i18n="${titleKey}">${tr(titleKey)}</span>${val}</span>${optional}</button>`;}
function rowDesc(titleKey,descKey,cmd,name,extraClass='',tail=''){return `<button class="tree-row ${extraClass}" data-command="${cmd}">${svg(name)}<span class="row-copy"><span data-i18n="${titleKey}">${tr(titleKey)}</span><small data-i18n="${descKey}">${tr(descKey)}</small></span>${tail}</button>`;}
function skillRow(){return `<div class="tree-row skill-row">${svg('file')}<span class="row-copy"><span id="skillLabel" data-i18n="sb.installSkillTitle">${tr('sb.installSkillTitle')}</span><small data-i18n="sb.installSkillDesc">${tr('sb.installSkillDesc')}</small></span><button type="button" role="switch" aria-checked="false" aria-labelledby="skillLabel" class="skill-toggle" id="skillStatus" disabled><span></span></button></div>`;}
function firmwareRow(){const fw=v.cubemxFirmware;if(v.cubemxFirmwareError)return '<small class="cubemx-status" title="'+esc(v.cubemxFirmwareError)+'">'+tr('cubemx.firmwareUnknown')+'</small>';if(!fw)return '';const label='STM32Cube '+fw.family+(fw.requiredVersion?' V'+fw.requiredVersion:'');return '<div class="cubemx-firmware"><small title="'+esc(fw.repository)+'">'+esc(label)+' · '+tr(fw.installed?'cubemx.firmwareInstalled':'cubemx.firmwareMissing')+'</small>'+(!fw.installed?'<button class="mini primary" data-command="mcu-vscode.installCubeMxFirmware" data-i18n="cubemx.installFirmware">'+tr('cubemx.installFirmware')+'</button>':'')+'</div>';}
function svdRow(){return `<div class="tree-row svd-config-row"><button class="svd-card-select" id="svdSelect" type="button">${svg('svd')}<span class="row-copy"><span data-i18n="svd.selectConfig">${tr('svd.selectConfig')}</span><small class="svd-status" id="svdStatus" data-i18n="svd.notConfigured">${tr('svd.notConfigured')}</small></span></button><span class="svd-row-actions"><span class="tag" data-i18n="common.optional">${tr('common.optional')}</span><button class="mini primary" id="svdDownload" type="button" data-i18n="svd.downloadOfficial">${tr('svd.downloadOfficial')}</button></span></div>`;}
return `<!doctype html><html lang="${L==='zh'?'zh-CN':'en'}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none';script-src 'unsafe-inline';style-src 'unsafe-inline';"><title>MCU Tools</title><style>
${sidebarCss}
</style></head><body><header class="toolbar"><span class="mark">EP</span><strong>EmberProbe</strong><button class="lang-toggle" id="langToggle" type="button" data-i18n-title="common.langTitle" title="${tr('common.langTitle')}" aria-label="${tr('common.langTitle')}"></button><i class="status-dot" id="statusDot" data-i18n-title="sb.connecting" title="${tr('sb.connecting')}"></i></header>
<div class="tree">${skillRow()}</div>
<section class="openocd-card checking" id="openocdCard"><div class="openocd-head"><i class="openocd-state"></i><span data-i18n="sb.openocdEnv">${tr('sb.openocdEnv')}</span></div><div class="openocd-message" id="openocdMessage">${tr('oc.checking')}</div><div class="openocd-actions"><button class="mini primary install-action" id="openocdInstall" data-i18n="sb.install">${tr('sb.install')}</button><button class="mini select-action" id="openocdSelect" data-i18n="sb.selectPath">${tr('sb.selectPath')}</button><button class="mini" id="openocdCheck" data-i18n="sb.recheck">${tr('sb.recheck')}</button></div></section><section class="feedback-prompt" id="feedbackPrompt" hidden></section>
<details open><summary data-i18n="sb.mcuConfig">${tr('sb.mcuConfig')}</summary><div class="tree">${rowDesc('sb.autoDetectTitle','sb.autoDetectDesc','mcu-vscode.autoDetect','scan','auto-row')}<div data-i18n="sb.manualConfig" class="tree-divider">${tr('sb.manualConfig')}</div>${rowVal('sb.selectElf',v.elf,'mcu-vscode.selectElf','file')}${rowVal('sb.selectDebugger',v.debugger,'mcu-vscode.selectDebugger','probe')}${rowVal('sb.selectMcu',v.mcu,'mcu-vscode.selectMcuCore','chip')}</div><div class="config-more-wrap"><details class="chip-more config-more" id="otherConfig"><summary data-i18n="sb.otherConfig">${tr('sb.otherConfig')}</summary><div class="tree">${svdRow()}${rowVal('cubemx.path',v.cubemxPath,'mcu-vscode.selectCubeMx','cube','<span class="tag" data-i18n="common.optional">'+tr('common.optional')+'</span>')}${rowVal('cubemx.ioc',v.iocPath,'mcu-vscode.selectIoc','ioc','<span class="tag" data-i18n="common.optional">'+tr('common.optional')+'</span>')}<small class="cubemx-status">${esc(v.cubemxStatus || '')}</small>${firmwareRow()}</div></details></div></details><details open><summary data-i18n="sb.chipInfo">${tr('sb.chipInfo')}</summary><div class="chip-box"><div class="chip-head"><i class="chip-state" id="chipState"></i><span class="chip-label" id="chipLabel">${tr('sb.notConnected')}</span><span class="live-actions"><button class="mini primary" id="chipRead">${tr('sb.read')}</button></span></div><div class="chip-body" id="chipBody"><div class="empty" data-i18n="sb.chipEmpty">${tr('sb.chipEmpty')}</div></div></div></details>
<details open><summary data-i18n="sb.liveValues">${tr('sb.liveValues')}</summary><div class="live-box"><div class="live-head"><i class="live-state" id="liveState"></i><span class="live-label" id="liveLabel">${tr('sb.waiting')}</span><span class="live-actions"><button class="mini primary" id="liveToggle">${tr('sb.start')}</button><button class="mini" data-command="mcu-vscode.openLiveWatch" data-i18n="sb.chart">${tr('sb.chart')}</button></span></div><div class="section-label"><button class="list-fold" id="watchFold" type="button" data-i18n-title="sb.foldList" title="${tr('sb.foldList')}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-6.5 10-6.5S22 12 22 12s-3.5 6.5-10 6.5S2 12 2 12z"/><circle cx="12" cy="12" r="2.7"/></svg></button><span data-i18n="sb.watchList">${tr('sb.watchList')}</span> <span class="count" id="watchCount">0</span></div><div class="values" id="liveValues"><div class="empty" data-i18n="sb.watchEmpty">${tr('sb.watchEmpty')}</div></div><div class="section-label"><button class="list-fold" id="writeFold" type="button" data-i18n-title="sb.foldList" title="${tr('sb.foldList')}"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.5-6.5 10-6.5S22 12 22 12s-3.5 6.5-10 6.5S2 12 2 12z"/><circle cx="12" cy="12" r="2.7"/></svg></button><span data-i18n="sb.writeList">${tr('sb.writeList')}</span> <span class="count" id="writeCount">0</span><span class="write-feedback" id="writeFeedback"></span></div><div class="values" id="writeValues"><div class="empty" data-i18n="sb.writeEmpty">${tr('sb.writeEmpty')}</div></div><details class="variable-browser" open><summary><span data-i18n="sb.allVars">${tr('sb.allVars')}</span> <span class="count" id="allCount">0</span><button class="mini var-refresh" id="varRefresh" type="button" data-i18n-title="sb.refreshVars" title="${tr('sb.refreshVars')}" aria-label="${tr('sb.refreshVars')}">↻</button></summary><div class="browser-body"><div class="filter-wrap"><input class="var-search" id="varSearch" data-i18n-ph="sb.varSearch" placeholder="${tr('sb.varSearch')}"><button class="filter-clear" id="varSearchClear" type="button" data-i18n-title="lw.clearFilter" title="${tr('lw.clearFilter')}" aria-label="${tr('lw.clearFilter')}">×</button></div><div class="available-head"><span data-i18n="common.variable">${tr('common.variable')}</span><span data-i18n="common.type">${tr('common.type')}</span><span data-i18n="common.address">${tr('common.address')}</span></div><div class="available" id="availableVars"><div class="empty" data-i18n="sb.varsLoading">${tr('sb.varsLoading')}</div></div><div class="resize-handle" id="varResizeHandle" data-i18n-title="sb.resizeHint" title="${tr('sb.resizeHint')}"></div></div></details></div></details>
<div class="primary-actions"><button class="action" data-command="mcu-vscode.download" data-i18n="sb.download">${tr('sb.download')}</button><button class="action secondary" data-command="mcu-vscode.debug" data-i18n="sb.debug">${tr('sb.debug')}</button></div><div class="log" id="openocdLog"></div><footer class="foot"><b>●</b><span id="statusText">${tr('sb.footConnecting')}</span></footer>

<script>window.__LANG__=${jsonForScript(L)};window.__I18N__=${i18nJson};</script>
<script>
${sidebarRenderer}
</script></body></html>`;}
module.exports={getModernWebviewContent,shiftSliderBounds};
