"use strict";
function esc(v){return String(v||'未选择').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const icon={scan:'<path d="M4 8V4h4m8 0h4v4m0 8v4h-4M8 20H4v-4M8 12h8m-4-4v8"/>',file:'<path d="M6 2h8l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/>',probe:'<rect x="5" y="7" width="14" height="10" rx="1"/><path d="M9 3v4m6-4v4M9 17v4m6-4v4M2 10h3m14 0h3M2 14h3m14 0h3"/>',chip:'<rect x="7" y="7" width="10" height="10" rx="1"/><path d="M9 2v3m6-3v3M9 19v3m6-3v3M2 9h3m-3 6h3m14-6h3m-3 6h3"/>',register:'<path d="M5 3h14v18H5zM9 3v18M9 8h10M9 13h10M9 18h10"/>',flash:'<path d="M13 2 5 14h7l-1 8 8-12h-7z"/>',debug:'<path d="M8 9h8v8H8zM9 3l3 3 3-3M4 12H1m22 0h-3M5 7 3 5m16 2 2-2M5 17l-2 2m16-2 2 2"/>'};
function svg(name){return `<svg viewBox="0 0 24 24" aria-hidden="true">${icon[name]}</svg>`;}
function row(title,value,cmd,name,optional=''){return `<button class="tree-row" data-command="${cmd}">${svg(name)}<span class="row-copy"><span>${title}</span><small title="${esc(value)}">${esc(value)}</small></span>${optional}</button>`;}
function getModernWebviewContent(v){return `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none';script-src 'unsafe-inline';style-src 'unsafe-inline';"><title>MCU Tools</title><style>
*{box-sizing:border-box}body{margin:0;padding:4px 0 12px;color:var(--vscode-sideBar-foreground,var(--vscode-foreground));background:var(--vscode-sideBar-background);font:13px/1.35 var(--vscode-font-family);user-select:none}.toolbar{display:flex;align-items:center;height:35px;padding:0 10px;border-bottom:1px solid var(--vscode-sideBarSectionHeader-border,transparent)}.mark{display:grid;place-items:center;width:24px;height:24px;margin-right:8px;border-radius:3px;color:white;background:#03234b;font-size:9px;font-weight:800;letter-spacing:-.06em}.toolbar strong{font-size:12px;font-weight:600}.status{margin-left:auto;width:7px;height:7px;border-radius:50%;background:var(--vscode-charts-yellow)}.status.ready{background:var(--vscode-testing-iconPassed)}.status.error{background:var(--vscode-errorForeground)}
details{border-bottom:1px solid var(--vscode-sideBarSectionHeader-border,transparent)}summary{display:flex;align-items:center;height:24px;padding:0 8px;color:var(--vscode-sideBarSectionHeader-foreground);background:var(--vscode-sideBarSectionHeader-background);font-size:11px;font-weight:700;text-transform:uppercase;cursor:pointer;list-style:none}summary::-webkit-details-marker{display:none}summary:before{content:'›';margin-right:5px;font-size:15px;transform:rotate(0);transition:transform .1s}details[open] summary:before{transform:rotate(90deg)}.tree{padding:3px 0 5px}.tree-row{display:flex;align-items:center;width:100%;min-height:40px;padding:3px 9px 3px 18px;border:1px solid transparent;color:inherit;background:transparent;font:inherit;text-align:left;cursor:pointer}.tree-row:hover{background:var(--vscode-list-hoverBackground)}.tree-row:focus-visible{outline:none;border-color:var(--vscode-focusBorder);background:var(--vscode-list-focusBackground);color:var(--vscode-list-focusForeground)}.tree-row svg{width:17px;height:17px;margin-right:8px;fill:none;stroke:currentColor;stroke-width:1.5;flex:none}.row-copy{min-width:0;display:flex;flex-direction:column}.row-copy>span{white-space:nowrap}.row-copy small{max-width:100%;overflow:hidden;color:var(--vscode-descriptionForeground);font:11px var(--vscode-editor-font-family);text-overflow:ellipsis;white-space:nowrap}.tag{margin-left:auto;padding:1px 5px;border:1px solid var(--vscode-widget-border);border-radius:8px;color:var(--vscode-descriptionForeground);font-size:9px}.primary-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:10px}.action{height:31px;border:0;border-radius:2px;color:var(--vscode-button-foreground);background:var(--vscode-button-background);font:12px var(--vscode-font-family);font-weight:600;cursor:pointer}.action:hover{background:var(--vscode-button-hoverBackground)}.action.secondary{color:var(--vscode-button-secondaryForeground);background:var(--vscode-button-secondaryBackground)}.action.secondary:hover{background:var(--vscode-button-secondaryHoverBackground)}.action:focus-visible{outline:1px solid var(--vscode-focusBorder);outline-offset:2px}.log{margin:0 10px 7px;padding:7px 8px;border-left:2px solid var(--vscode-focusBorder);background:var(--vscode-textCodeBlock-background);font:11px/1.45 var(--vscode-editor-font-family);white-space:pre-wrap}.log:empty{display:none}.log .success{color:var(--vscode-testing-iconPassed)}.log .error{color:var(--vscode-errorForeground)}.foot{display:flex;align-items:center;gap:6px;padding:2px 11px;color:var(--vscode-descriptionForeground);font-size:10px}.foot span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}@media(max-width:210px){.primary-actions{grid-template-columns:1fr}.tree-row{padding-left:10px}}
</style></head><body><header class="toolbar"><span class="mark">EP</span><strong>EmberProbe</strong><i class="status" id="status" title="正在连接"></i></header>
<div class="tree">${row('自动检测配置','扫描 ELF、MCU 与调试器','mcu-vscode.autoDetect','scan')}${row('安装 Agent Skill','让 Agent 能安全下载固件','mcu-vscode.installAgentSkill','file')}</div>
<details open><summary>MCU 配置</summary><div class="tree">${row('选择 ELF 固件',v.elf,'mcu-vscode.selectElf','file')}${row('选择调试器',v.debugger,'mcu-vscode.selectDebugger','probe')}${row('选择 MCU 目标',v.mcu,'mcu-vscode.selectMcuCore','chip')}${row('选择 SVD 文件',v.svd,'mcu-vscode.selectSvd','register','<span class="tag">可选</span>')}</div></details>
<details open><summary>关键操作</summary><div class="tree">${row('下载程序','使用 OpenOCD 写入目标芯片','mcu-vscode.download','flash')}${row('启动调试','使用 Cortex-Debug 启动会话','mcu-vscode.debug','debug')}</div></details>
<div class="primary-actions"><button class="action" data-command="mcu-vscode.download">下载</button><button class="action secondary" data-command="mcu-vscode.debug">调试</button></div><div class="log" id="openocdLog"></div><footer class="foot"><b>●</b><span id="statusText">正在连接扩展服务…</span></footer>
<script>const api=window.acquireVsCodeApi?window.acquireVsCodeApi():null,dot=document.getElementById('status'),text=document.getElementById('statusText'),log=document.getElementById('openocdLog');function state(k,t){dot.className='status '+k;dot.title=t;text.textContent=t}function progress(m){state(m.level==='error'?'error':m.level==='success'?'ready':'',m.message);const line=document.createElement('div');line.className=m.level||'';line.textContent='• '+m.message;log.appendChild(line);while(log.children.length>6)log.firstChild.remove()}document.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>{if(!api)return state('error','扩展服务未连接');if(b.dataset.command==='mcu-vscode.download')log.textContent='';state('','正在执行…');api.postMessage({type:'executeCommand',cmd:b.dataset.command})});window.addEventListener('message',e=>{const m=e.data;if(m.type==='initSuccess')state('ready','扩展服务已就绪');else if(m.type==='openocdProgress')progress(m);else if(m.type==='commandSuccess')state('ready','操作已完成');else if(m.type==='commandError')state('error',m.error||'操作失败')});if(api)api.postMessage({type:'initCheck'});else state('error','无法连接 VS Code API');</script></body></html>`;}
module.exports={getModernWebviewContent};
